#!/bin/sh

# It is authored by Mosky Liu <mosky.tw@gmail.com>.

### BEGIN INIT INFO
# Provides:          uwsgi-emperor
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the uWSGI app server
# Description:       starts uWSGI app server using start-stop-daemon
### END INIT INFO

PATH=/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=`which uwsgi`
NAME=uwsgi-emperor
DESC=uwsgi-emperor

VASSALS=/etc/uwsgi-emperor
PIDFILE=/run/uwsgi-emperor.pid
LOGFILE=/var/log/uwsgi-emperor.log

# Include uwsgi defaults if available
if [ -f /etc/default/uwsgi-emperor ]
then
    . /etc/default/uwsgi-emperor
fi

test -x "$DAEMON" || exit 1
test -d "$VASSALS" || mkdir -p $VASSALS

set -e

. /lib/lsb/init-functions

start() {
    start-stop-daemon --start --quiet --pidfile $PIDFILE \
        --retry 5 --exec $DAEMON --oknodo \
        -- \
        --emperor "$VASSALS" --pidfile "$PIDFILE" \
        --daemonize "$LOGFILE" \
        --die-on-term
}

stop() {
    start-stop-daemon --stop --quiet --pidfile $PIDFILE \
        --retry 5 --exec $DAEMON --oknodo
}

reload() {
    start-stop-daemon --stop --signal HUP --quiet --pidfile $PIDFILE \
        --oknodo --exec $DAEMON
}

case $1 in
    start)
        log_daemon_msg "Starting $DESC" "$NAME"
        start
        log_end_msg $?
        ;;
    stop)
        log_daemon_msg "Stopping $DESC" "$NAME"
        stop
        log_end_msg $?
        ;;
    restart|force-reload)
        log_daemon_msg "Restarting $DESC" "$NAME"
        stop
        sleep 1
        start
        log_end_msg $?
        ;;
    reload)
        log_daemon_msg "Reloading $DESC configuration" "$NAME"
        reload
        log_end_msg $?
        ;;
    status)
        status_of_proc -p "$PIDFILE" "$DAEMON" "$NAME"
        ;;
    *)
        echo "Usage: $NAME {start|stop|restart|reload|force-reload|statu}" >&2
        exit 1
        ;;
esac
exit 0
